### ISSUE TITLE
{ backlinks: 'fake' } gets passed by checkMethods when initialising nested scuttle-* modules

### ISSUE THREAD

**Issue by m4gpi** [ssbc/scuttle-inject#2]
Using nested injections - `scuttle-dark-crystal` uses `scuttle-invite` inside it's code-base. Error thrown:

```
Error: scuttle-inject requires a scuttlebot server with the private plugin installed
    at pluginDeps.forEach.p (/home/kyphae/Projects/scuttle-dark-crystal/node_modules/scuttle-inject/index.js:86:27)
    at Array.forEach (<anonymous>)
    at checkPlugins (/home/kyphae/Projects/scuttle-dark-crystal/node_modules/scuttle-inject/index.js:85:14)
    at inject (/home/kyphae/Projects/scuttle-dark-crystal/node_modules/scuttle-inject/index.js:18:7)
    at module.exports (/home/kyphae/Projects/scuttle-dark-crystal/node_modules/scuttle-invite/index.js:8:10)
    at module.exports (/home/kyphae/Projects/scuttle-dark-crystal/request/async/request.js:11:19)
    at each (/home/kyphae/Projects/scuttle-dark-crystal/node_modules/scuttle-inject/index.js:79:28)
    at each (/home/kyphae/Projects/scuttle-dark-crystal/node_modules/libnested/index.js:36:20)
    at each (/home/kyphae/Projects/scuttle-dark-crystal/node_modules/libnested/index.js:34:20)
    at each (/home/kyphae/Projects/scuttle-dark-crystal/node_modules/libnested/index.js:34:20)
    at checkMethods (/home/kyphae/Projects/scuttle-dark-crystal/node_modules/scuttle-inject/index.js:77:3)
    at inject (/home/kyphae/Projects/scuttle-dark-crystal/node_modules/scuttle-inject/index.js:12:3)
    at module.exports (/home/kyphae/Projects/scuttle-dark-crystal/index.js:14:10)
    at Array.darkCrystalPage (/home/kyphae/Projects/patchbay-dark-crystal/plugs/app/dark-crystal.js:38:21)
    at Array.<anonymous> (/home/kyphae/Projects/patchbay/node_modules/depject/apply.js:18:30)
    at Router (/home/kyphae/Projects/patchbay/router/async/router.js:34:33)
```

Reason for this is `checkMethods` passes `{ backlinks: 'fake' }` object when testing to see if the initial injection works. This has a knock-on effect of causing the nested scuttle module to fail here:

https://github.com/ssbc/scuttle-inject/blob/5db33c863073e1ea89ef932d0f7e16b1e6eca33b/index.js#L79

```js
function checkPlugins (server, pluginDeps) {
  pluginDeps.forEach(p => {
    if (!server[p]) throw new Error(`${name} requires a scuttlebot server with the ${p} plugin installed`)
  })
}
```

Quick fix:

```js
function checkPlugins (server, pluginDeps) {
  if (server.backlinks === "fake") return
  pluginDeps.forEach(p => {
    if (!server[p]) throw new Error(`${name} requires a scuttlebot server with the ${p} plugin installed`)
  })
}
```

**Comment by m4gpi** [comment]
Made a better fix, fakes out _all_ dependencies passed in instead of returning if just `{ backlinks: 'fake' }`, which is presumptuous. This means the nested `scuttle-*` module will also be properly checked.

```js
function checkMethods (methods, pluginDeps) {
   const fakeServer = pluginDeps.reduce((obj, p) => Object.assign(obj, { [p]: 'fake' }), {}) 
   ...
}

function checkPlugins (server, pluginDeps) { 
  pluginDeps.forEach(p => {
    if (server[p] === "fake") { return } 
    ...
  })
}
```

**Comment by mixmix** [comment]
Damn I wish I'd seen this.
I went and stumbled on the same problem and fixed it then was confused when I had merge conflicts.
Can you please not merge things if you can't publish them at the same time xxx

added you to scuttle-inject on npm
published work cc @KGibb8
